### ISSUE TITLE
Question about helpers

### ISSUE THREAD

**Issue by open-it** [DASPRiD/Formidable#17]
I am trying your lib for a small project and I don't really get why you need to format the html errors with htmlspecialchars ? This enforce me to do a | raw in my view (I try it with zend expressive and twig).

https://github.com/DASPRiD/Formidable/blob/00610576fc5f1e2908a4533518247bdcc0d952c0/src/Helper/ErrorList.php#L40

**Comment by DASPRiD** [comment]
Because the ErrorList helper, like all helpers, returns valid HTML, not plain text.
